/* eslint-disable @typescript-eslint/no-empty-interface */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/comments": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.comments.id"];
          user_id?: parameters["rowFilter.comments.user_id"];
          content?: parameters["rowFilter.comments.content"];
          site_id?: parameters["rowFilter.comments.site_id"];
          content_id?: parameters["rowFilter.comments.content_id"];
          created_at?: parameters["rowFilter.comments.created_at"];
          parent_id?: parameters["rowFilter.comments.parent_id"];
          ip?: parameters["rowFilter.comments.ip"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["comments"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** comments */
          comments?: definitions["comments"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.comments.id"];
          user_id?: parameters["rowFilter.comments.user_id"];
          content?: parameters["rowFilter.comments.content"];
          site_id?: parameters["rowFilter.comments.site_id"];
          content_id?: parameters["rowFilter.comments.content_id"];
          created_at?: parameters["rowFilter.comments.created_at"];
          parent_id?: parameters["rowFilter.comments.parent_id"];
          ip?: parameters["rowFilter.comments.ip"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.comments.id"];
          user_id?: parameters["rowFilter.comments.user_id"];
          content?: parameters["rowFilter.comments.content"];
          site_id?: parameters["rowFilter.comments.site_id"];
          content_id?: parameters["rowFilter.comments.content_id"];
          created_at?: parameters["rowFilter.comments.created_at"];
          parent_id?: parameters["rowFilter.comments.parent_id"];
          ip?: parameters["rowFilter.comments.ip"];
        };
        body: {
          /** comments */
          comments?: definitions["comments"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/sites": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sites.id"];
          title?: parameters["rowFilter.sites.title"];
          origin?: parameters["rowFilter.sites.origin"];
          created_at?: parameters["rowFilter.sites.created_at"];
          user_id?: parameters["rowFilter.sites.user_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["sites"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** sites */
          sites?: definitions["sites"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferPost"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sites.id"];
          title?: parameters["rowFilter.sites.title"];
          origin?: parameters["rowFilter.sites.origin"];
          created_at?: parameters["rowFilter.sites.created_at"];
          user_id?: parameters["rowFilter.sites.user_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.sites.id"];
          title?: parameters["rowFilter.sites.title"];
          origin?: parameters["rowFilter.sites.origin"];
          created_at?: parameters["rowFilter.sites.created_at"];
          user_id?: parameters["rowFilter.sites.user_id"];
        };
        body: {
          /** sites */
          sites?: definitions["sites"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
}

export interface definitions {
  comments: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: uuid */
    user_id?: string;
    /** Format: text */
    content: string;
    /**
     * Format: bigint
     * @description Note:
     * This is a Foreign Key to `sites.id`.<fk table='sites' column='id'/>
     */
    site_id: number;
    /** Format: text */
    content_id: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: bigint */
    parent_id?: number;
    /** Format: text */
    ip?: string;
  };
  /** @description Sites that uses supacus */
  sites: {
    /**
     * Format: bigint
     * @description Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /** Format: text */
    title: string;
    /** Format: text */
    origin: string;
    /**
     * Format: timestamp with time zone
     * @default now()
     */
    created_at?: string;
    /** Format: uuid */
    user_id: string;
  };
}

export interface parameters {
  /**
   * @description Preference
   * @enum {string}
   */
  preferParams: "params=single-object";
  /**
   * @description Preference
   * @enum {string}
   */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferCount: "count=none";
  /**
   * @description Preference
   * @enum {string}
   */
  preferPost:
    | "return=representation"
    | "return=minimal"
    | "return=none"
    | "resolution=ignore-duplicates"
    | "resolution=merge-duplicates";
  /** @description Filtering Columns */
  select: string;
  /** @description On Conflict */
  on_conflict: string;
  /** @description Ordering */
  order: string;
  /** @description Limiting and Pagination */
  range: string;
  /**
   * @description Limiting and Pagination
   * @default items
   */
  rangeUnit: string;
  /** @description Limiting and Pagination */
  offset: string;
  /** @description Limiting and Pagination */
  limit: string;
  /** @description comments */
  "body.comments": definitions["comments"];
  /** Format: bigint */
  "rowFilter.comments.id": string;
  /** Format: uuid */
  "rowFilter.comments.user_id": string;
  /** Format: text */
  "rowFilter.comments.content": string;
  /** Format: bigint */
  "rowFilter.comments.site_id": string;
  /** Format: text */
  "rowFilter.comments.content_id": string;
  /** Format: timestamp with time zone */
  "rowFilter.comments.created_at": string;
  /** Format: bigint */
  "rowFilter.comments.parent_id": string;
  /** Format: text */
  "rowFilter.comments.ip": string;
  /** @description sites */
  "body.sites": definitions["sites"];
  /** Format: bigint */
  "rowFilter.sites.id": string;
  /** Format: text */
  "rowFilter.sites.title": string;
  /** Format: text */
  "rowFilter.sites.origin": string;
  /** Format: timestamp with time zone */
  "rowFilter.sites.created_at": string;
  /** Format: uuid */
  "rowFilter.sites.user_id": string;
}

export interface operations {}

export interface external {}
